### ISSUE TITLE
Sidebar gone even after timer?

### ISSUE THREAD

**Issue by spekulatius** [AustinMoninger/twitter-free-mornings#2]
Hey @AustinMoninger 

my side bar with search, trending etc. is permanently gone when using the plugin. Is this intended?

Cheers!

**Comment by AustinMoninger** [comment]
Hey @spekulatius !

Removing the Trending and Who to Follow tabs on the sidebar was intentional (it's mentioned on the web store description). Removing the search was less intentional and I found myself going to the Explore tab to do that, so I just pushed a fix and submitted a new version to the Chrome Web Store in order to bring the search bar back.

Does that work for you? Do you find the Trending and Who to Follow tabs valuable?

**Comment by spekulatius** [comment]
No, I'm actually not worried about the trending and who to follow sections. Only the search. I'll update the FF version with the latest code

**Comment by spekulatius** [comment]
Submitted 💪️
